[package]
name = "plan-widget-wasm"
version = "0.1.0"
authors = ["Dylan Lewis <dylan_lewis93@web.de>"]
edition = "2018"

[lib]
path = "src/rust/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.74"
chrono = "0.4.19"
serde = "1.0.134"
serde-wasm-bindgen = "0.4.1"